# Generated by Django 3.2.4 on 2021-08-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210720_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mm',
            options={'ordering': ['-published'], 'verbose_name': 'Книгy', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='mm',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор'),
        ),
    ]
