# Generated by Django 3.2.6 on 2021-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210803_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mm',
            name='strings',
        ),
        migrations.AddField(
            model_name='mm',
            name='epub',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='epub'),
        ),
        migrations.AddField(
            model_name='mm',
            name='fb2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fb2'),
        ),
        migrations.AddField(
            model_name='mm',
            name='mobi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mobi'),
        ),
        migrations.AddField(
            model_name='mm',
            name='pdf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pdf'),
        ),
    ]
