# Generated by Django 3.2.7 on 2021-11-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210828_1750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mm',
            new_name='Books',
        ),
    ]
