# Generated by Django 3.2.4 on 2021-07-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='суть')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата публикации')),
            ],
        ),
    ]
