# Generated by Django 3.2.7 on 2021-09-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='уровень подготовки')),
            ],
            options={
                'verbose_name': 'Классы',
                'verbose_name_plural': 'Класс',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500, null=True, verbose_name='задача')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.level', verbose_name='уровень подготовки')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задача',
                'ordering': ['level'],
            },
        ),
    ]
