# Generated by Django 3.2.7 on 2021-11-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500, null=True, verbose_name='задача')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задача',
                'ordering': ['task'],
            },
        ),
        migrations.RemoveField(
            model_name='tt',
            name='level',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Tt',
        ),
    ]
