# Generated by Django 3.2.7 on 2021-11-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
