# Generated by Django 3.2.7 on 2021-11-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=150, verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответ',
                'ordering': ['ans'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.answer', verbose_name='ответ'),
        ),
    ]
