# Generated by Django 3.2.4 on 2021-08-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='уровень подготовки')),
            ],
            options={
                'verbose_name': 'Классы',
                'verbose_name_plural': 'Класс',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, null=True, verbose_name='URl-адрес')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.level', verbose_name='уровень подготовки')),
            ],
            options={
                'verbose_name': 'Уроки',
                'verbose_name_plural': 'Урок',
                'ordering': ['level'],
            },
        ),
    ]
