# Generated by Django 3.2.7 on 2021-11-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=250, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, null=True, verbose_name='URl-адрес')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Уроки',
                'verbose_name_plural': 'Урок',
                'ordering': ['category'],
            },
        ),
        migrations.RemoveField(
            model_name='ll',
            name='level',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Ll',
        ),
    ]
