# Generated by Django 3.2.7 on 2021-11-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20211103_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='category',
            new_name='tag',
        ),
    ]
