# Generated by Django 3.2.7 on 2021-11-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessons_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['-published'], 'verbose_name': 'Уроки', 'verbose_name_plural': 'Урок'},
        ),
        migrations.AddField(
            model_name='lessons',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='дата публикации'),
        ),
    ]
